name: Copy files then commit change
description: Move the kube manifests to kustomize base folder of deployment repo, then commit if changed.
author: touchground

inputs:
  source:
    description: Source path location
    required: false
    default:  ""
  target:
    description: Target path location
    required: false
    default:  ""
  message:
    description: Commit message
    required: false
    defautl: "auto commit by GitHub Action [bot]"

outputs:
  output:
    description: True = changes to manifest files (commit to local branch), False = No change.
    value: ${{ steps.cp_commit.outputs.output }}


runs:
  using: composite
  steps:
    - name: copy & commit
      id: cp_commit
      run: |
        set -e;
        SOURCE=${{ inputs.source }}
        TARGET=${{ inputs.target }}
        mkdir -p $TARGET

        if [ "$SOURCE" = "" ]; then
          # Just git commit 
        elif [ $(echo $SOURCE | egrep '.yaml$') ]; then
          cp -f $SOURCE $TARGET
        elif [ -n "$SOURCE" ] && [ -d "$SOURCE" ]; then
          cp -f $SOURCE/*.yaml $TARGET
        else
          echo "Source does not exist: $SOURCE"
          exit 1;
        fi

        git config --local user.email "$(git show -s --format='%ae' HEAD)";
        git config --local user.name  "$(git show -s --format='%an' HEAD)";

        git add .

        if [ ! "$(git status | grep 'nothing to commit')" ]; then
          git commit -m "${{ inputs.message }}"
          echo "output=true" >> $GITHUB_OUTPUT
        else
          echo "No changes to commit."
          echo "output=false" >> $GITHUB_OUTPUT
        fi
      shell: bash